// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'frb.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `db`, `runtime`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `from`, `from`, `from`, `from`

/// Initialize the FFI backend with database at the given path
/// Must be called before any other FFI functions
Future<String> initBackend({required String dbPath}) =>
    RustLib.instance.api.crateApiFrbInitBackend(dbPath: dbPath);

/// Check if the FFI backend is healthy
String healthCheck() => RustLib.instance.api.crateApiFrbHealthCheck();

/// Get the FFI backend version
String getVersion() => RustLib.instance.api.crateApiFrbGetVersion();

/// Simple greeting function to test the bridge
String greet({required String name}) =>
    RustLib.instance.api.crateApiFrbGreet(name: name);

/// Create a new book
Future<FrbBook> createBook({required FrbBook book}) =>
    RustLib.instance.api.crateApiFrbCreateBook(book: book);

/// Get all books with optional filters
Future<List<FrbBook>> getAllBooks({
  String? status,
  String? title,
  String? tag,
}) => RustLib.instance.api.crateApiFrbGetAllBooks(
  status: status,
  title: title,
  tag: tag,
);

/// Get a single book by ID
Future<FrbBook> getBookById({required int id}) =>
    RustLib.instance.api.crateApiFrbGetBookById(id: id);

/// Update an existing book
Future<FrbBook> updateBook({required int id, required FrbBook book}) =>
    RustLib.instance.api.crateApiFrbUpdateBook(id: id, book: book);

/// Delete a book
Future<void> deleteBook({required int id}) =>
    RustLib.instance.api.crateApiFrbDeleteBook(id: id);

/// Count total books
Future<PlatformInt64> countBooks() =>
    RustLib.instance.api.crateApiFrbCountBooks();

/// Get all unique tags with counts
Future<List<(String, PlatformInt64)>> getAllTags() =>
    RustLib.instance.api.crateApiFrbGetAllTags();

/// Get all contacts with optional filters
Future<List<FrbContact>> getAllContacts({
  int? libraryId,
  String? contactType,
}) => RustLib.instance.api.crateApiFrbGetAllContacts(
  libraryId: libraryId,
  contactType: contactType,
);

/// Get a single contact by ID
Future<FrbContact> getContactById({required int id}) =>
    RustLib.instance.api.crateApiFrbGetContactById(id: id);

/// Count total contacts
Future<PlatformInt64> countContacts() =>
    RustLib.instance.api.crateApiFrbCountContacts();

/// Get all loans with optional filters
Future<List<FrbLoan>> getAllLoans({
  int? libraryId,
  String? status,
  int? contactId,
}) => RustLib.instance.api.crateApiFrbGetAllLoans(
  libraryId: libraryId,
  status: status,
  contactId: contactId,
);

/// Count active loans
Future<PlatformInt64> countActiveLoans() =>
    RustLib.instance.api.crateApiFrbCountActiveLoans();

/// Return a loan
Future<String> returnLoan({required int id}) =>
    RustLib.instance.api.crateApiFrbReturnLoan(id: id);

/// Simplified book structure for FFI
@freezed
sealed class FrbBook with _$FrbBook {
  const factory FrbBook({
    int? id,
    required String title,
    String? author,
    String? isbn,
    String? summary,
    String? publisher,
    int? publicationYear,
    String? coverUrl,
    String? largeCoverUrl,
    String? readingStatus,
    int? shelfPosition,
    int? userRating,
    String? subjects,
    String? createdAt,
    String? updatedAt,
    String? finishedReadingAt,
    String? startedReadingAt,
  }) = _FrbBook;
}

/// Simplified contact structure for FFI
@freezed
sealed class FrbContact with _$FrbContact {
  const factory FrbContact({
    int? id,
    required String contactType,
    required String name,
    String? firstName,
    String? email,
    String? phone,
    String? address,
    String? notes,
    required bool isActive,
  }) = _FrbContact;
}

/// Simplified loan structure for FFI
@freezed
sealed class FrbLoan with _$FrbLoan {
  const factory FrbLoan({
    required int id,
    required int copyId,
    required int contactId,
    required int libraryId,
    required String loanDate,
    required String dueDate,
    String? returnDate,
    required String status,
    String? notes,
    required String contactName,
    required String bookTitle,
  }) = _FrbLoan;
}
